# This file can be used by the VSCode REST Client extension
# for ad-hoc testing of either the graph or web microservices.
# See https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#
# Chris Joakim, Microsoft, 2025

http://127.0.0.1:8001/ping

###

http://127.0.0.1:8001/health

###

http://127.0.0.1:8001/reload_graph

###

http://127.0.0.1:8001/ontology


###

POST http://127.0.0.1:8001/sparql_query
User-Agent: VSC-REST-Client
content-type: application/json

{
    "sparql": "SELECT * WHERE { ?s ?p ?o . } LIMIT 10"
}

###

POST http://127.0.0.1:8001/sparql_query
User-Agent: VSC-REST-Client
content-type: application/json

{
    "sparql": "PREFIX c: <http://cosmosdb.com/caig#> SELECT ?used_library WHERE { <http://cosmosdb.com/caig/pypi_flask> c:uses_library ?used_library . } LIMIT 10"
}

###


POST http://127.0.0.1:8001/sparql_bom_query
User-Agent: VSC-REST-Client
content-type: application/json

{
    "libname": "flask",
    "max_depth": 2
}


###

GET http://127.0.0.1:8000/ping

###

GET http://127.0.0.1:8000/liveness

###

GET http://127.0.0.1:8000/sparql_console


###

POST http://127.0.0.1:8001/sparql_query
User-Agent: VSC-REST-Client
content-type: application/json

{
    "sparql": "PREFIX caig: <http://cosmosdb.com/caig#> SELECT ?library (COUNT(?dependency) AS ?dependencyCount) WHERE {     ?library a caig:Library .     ?library caig:uses_library ?dependency . } GROUP BY ?library ORDER BY DESC(?dependencyCount) LIMIT 5"
}
