# PowerShell script to set the necessary CAIG_ environment variables,
# generated by main.py on Sat Mar  8 18:14:39 2025
# Edit ALL of these generated values per your actual deployment.

echo "Setting CAIG environment variables (only missing variables will be added)"

# Helper: set a user environment variable only if it does not already exist or is empty
function Set-EnvIfMissing {
	param(
		[string]$Name,
		[string]$Value,
		[ValidateSet('User','Machine','Process')]
		[string]$Target = 'User',
		[switch]$WarnIfEmpty
	)

	# Read the current value from the chosen target scope
	try {
		$current = [Environment]::GetEnvironmentVariable($Name, $Target)
	} catch {
		Write-Host "Failed to read environment variable '${Name}' in scope ${Target}: $_" -ForegroundColor Yellow
		$current = $null
	}

	if ([string]::IsNullOrEmpty($current)) {
		if ($Value -ne "") {
			[Environment]::SetEnvironmentVariable($Name, $Value, $Target)
			Write-Host "Set ${Name} = '$Value' (scope: ${Target})"
		} else {
			# Value is an empty placeholder; set only if user explicitly wants to set empty
			Write-Host "Skipped ${Name}: sample value is empty and variable was not present (scope: ${Target})" -ForegroundColor Cyan
			if ($WarnIfEmpty) { Write-Host "Note: ${Name} has an empty sample value - edit the script to provide a real value before setting." -ForegroundColor Yellow }
		}
	} else {
		Write-Host "Skipped ${Name}: already set to '$current' (scope: ${Target})" -ForegroundColor Green
	}
}

# Use the helper to set each variable only if missing
Set-EnvIfMissing -Name "CAIG_AZURE_OPENAI_COMPLETIONS_DEP" -Value "gpt-4.1"
Set-EnvIfMissing -Name "CAIG_AZURE_OPENAI_EMBEDDINGS_DEP" -Value "text-embedding-ada-002"
Set-EnvIfMissing -Name "CAIG_AZURE_OPENAI_KEY" -Value "" -WarnIfEmpty
Set-EnvIfMissing -Name "CAIG_AZURE_OPENAI_URL" -Value "" -WarnIfEmpty
Set-EnvIfMissing -Name "CAIG_CONFIG_CONTAINER" -Value "config"
Set-EnvIfMissing -Name "CAIG_CONVERSATIONS_CONTAINER" -Value "conversations"
Set-EnvIfMissing -Name "CAIG_COSMOSDB_NOSQL_ACCT" -Value "<your-account>" -WarnIfEmpty
Set-EnvIfMissing -Name "CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM" -Value "key"
Set-EnvIfMissing -Name "CAIG_COSMOSDB_NOSQL_KEY" -Value "" -WarnIfEmpty
Set-EnvIfMissing -Name "CAIG_COSMOSDB_NOSQL_RG" -Value "<your-resource-group>" -WarnIfEmpty
Set-EnvIfMissing -Name "CAIG_COSMOSDB_NOSQL_URI" -Value "https://<your-account>.documents.azure.com:443/" -WarnIfEmpty
Set-EnvIfMissing -Name "CAIG_FEEDBACK_CONTAINER" -Value "xxx"
Set-EnvIfMissing -Name "CAIG_GRAPH_DUMP_OUTFILE" -Value "tmp/model_dump.nt"
Set-EnvIfMissing -Name "CAIG_GRAPH_DUMP_UPON_BUILD" -Value "false"
Set-EnvIfMissing -Name "CAIG_GRAPH_NAMESPACE" -Value "http://cosmosdb.com/caig#"
Set-EnvIfMissing -Name "CAIG_GRAPH_SERVICE_NAME" -Value "caig-graph"
Set-EnvIfMissing -Name "CAIG_GRAPH_SERVICE_PORT" -Value "8001"
Set-EnvIfMissing -Name "CAIG_GRAPH_SERVICE_URL" -Value "http://127.0.0.1"
Set-EnvIfMissing -Name "CAIG_GRAPH_SOURCE_CONTAINER" -Value "libraries"
Set-EnvIfMissing -Name "CAIG_GRAPH_SOURCE_DB" -Value "caig"
Set-EnvIfMissing -Name "CAIG_GRAPH_SOURCE_OWL_FILENAME" -Value "ontologies/libraries.owl"
Set-EnvIfMissing -Name "CAIG_GRAPH_SOURCE_PATH" -Value "rdf/libraries-graph.nt"
Set-EnvIfMissing -Name "CAIG_GRAPH_SOURCE_TYPE" -Value "cosmos_nosql"
Set-EnvIfMissing -Name "CAIG_HOME" -Value "" -WarnIfEmpty
Set-EnvIfMissing -Name "CAIG_LOG_LEVEL" -Value "info"
Set-EnvIfMissing -Name "CAIG_WEBSVC_AUTH_HEADER" -Value "xxx"
Set-EnvIfMissing -Name "CAIG_WEBSVC_AUTH_VALUE" -Value "xxx"
Set-EnvIfMissing -Name "CAIG_WEB_APP_NAME" -Value "caig-web"
Set-EnvIfMissing -Name "CAIG_WEB_APP_PORT" -Value "8000"
Set-EnvIfMissing -Name "CAIG_WEB_APP_URL" -Value "http://127.0.0.1"

############### Prompts
Set-EnvIfMissing -Name "CAIG_PROMPT_SPARQL_PATH" -Value "prompts/gen_sparql_generic.txt"
Set-EnvIfMissing -Name "CAIG_PROMPT_COMPLETION_PATH" -Value "prompts/gen_completion_generic.txt"

############ Azure Deployment
Set-EnvIfMissing -Name "CAIG_ACA_ENVIRONMENT_NAME" -Value "caig"
Set-EnvIfMissing -Name "CAIG_AZURE_REGION" -Value "eastus"
Set-EnvIfMissing -Name "CAIG_DEFINED_AUTH_USERS" -Value "user1,user2,user3"
Set-EnvIfMissing -Name "CAIG_LA_WORKSPACE_NAME" -Value "caig"

