# Bash script to set the necessary CAIG_ environment variables,
# generated by main.py on Sat Mar  8 18:14:39 2025
# Edit ALL of these generated values per your actual deployment.

echo "Setting CAIG environment variables"

echo 'setting CAIG_AZURE_OPENAI_COMPLETIONS_DEP'
export CAIG_AZURE_OPENAI_COMPLETIONS_DEP="gpt4"

echo 'setting CAIG_AZURE_OPENAI_EMBEDDINGS_DEP'
export CAIG_AZURE_OPENAI_EMBEDDINGS_DEP="embeddings"

echo 'setting CAIG_AZURE_OPENAI_KEY'
export CAIG_AZURE_OPENAI_KEY=""

echo 'setting CAIG_AZURE_OPENAI_URL'
export CAIG_AZURE_OPENAI_URL=""

echo 'setting CAIG_CONFIG_CONTAINER'
export CAIG_CONFIG_CONTAINER="config"

echo 'setting CAIG_CONVERSATIONS_CONTAINER'
export CAIG_CONVERSATIONS_CONTAINER="conversations"

echo 'setting CAIG_COSMOSDB_NOSQL_ACCT'
export CAIG_COSMOSDB_NOSQL_ACCT="mycosmosdbnosqlacct"

echo 'setting CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM'
export CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM="key"

echo 'setting CAIG_COSMOSDB_NOSQL_KEY'
export CAIG_COSMOSDB_NOSQL_KEY=""

echo 'setting CAIG_COSMOSDB_NOSQL_RG'
export CAIG_COSMOSDB_NOSQL_RG="myresourcegroup"

echo 'setting CAIG_COSMOSDB_NOSQL_URI'
export CAIG_COSMOSDB_NOSQL_URI="https://<your-account>.documents.azure.com:443/"

echo 'setting CAIG_FEEDBACK_CONTAINER'
export CAIG_FEEDBACK_CONTAINER="xxx"

echo 'setting CAIG_GRAPH_DUMP_OUTFILE'
export CAIG_GRAPH_DUMP_OUTFILE="tmp/model_dump.nt"

echo 'setting CAIG_GRAPH_DUMP_UPON_BUILD'
export CAIG_GRAPH_DUMP_UPON_BUILD="false"

echo 'setting CAIG_GRAPH_NAMESPACE'
export CAIG_GRAPH_NAMESPACE="http://cosmosdb.com/caig#"

echo 'setting CAIG_GRAPH_SERVICE_NAME'
export CAIG_GRAPH_SERVICE_NAME="caig-graph"

echo 'setting CAIG_GRAPH_SERVICE_PORT'
export CAIG_GRAPH_SERVICE_PORT="8001"

echo 'setting CAIG_GRAPH_SERVICE_URL'
export CAIG_GRAPH_SERVICE_URL="http://127.0.0.1"

echo 'setting CAIG_GRAPH_SOURCE_CONTAINER'
export CAIG_GRAPH_SOURCE_CONTAINER="libraries"

echo 'setting CAIG_GRAPH_SOURCE_DB'
export CAIG_GRAPH_SOURCE_DB="caig"

echo 'setting CAIG_GRAPH_SOURCE_OWL_FILENAME'
export CAIG_GRAPH_SOURCE_OWL_FILENAME="ontologies/libraries.owl"

echo 'setting CAIG_GRAPH_SOURCE_PATH'
export CAIG_GRAPH_SOURCE_PATH="rdf/libraries-graph.nt"

echo 'setting CAIG_GRAPH_SOURCE_TYPE'
export CAIG_GRAPH_SOURCE_TYPE="cosmos_nosql"

echo 'setting CAIG_HOME'
export CAIG_HOME=""

echo 'setting CAIG_LOG_LEVEL'
export CAIG_LOG_LEVEL="info"

echo 'setting CAIG_WEBSVC_AUTH_HEADER'
export CAIG_WEBSVC_AUTH_HEADER="xxx"

echo 'setting CAIG_WEBSVC_AUTH_VALUE'
export CAIG_WEBSVC_AUTH_VALUE="xxx"

echo 'setting CAIG_WEB_APP_NAME'
export CAIG_WEB_APP_NAME="caig-web"

echo 'setting CAIG_WEB_APP_PORT'
export CAIG_WEB_APP_PORT="8000"

echo 'setting CAIG_WEB_APP_URL'
export CAIG_WEB_APP_URL="http://127.0.0.1"