# Bash script to set the necessary CAIG_ environment variables
# generated by main.py on Sat Mar  8 18:14:39 2025
# This script only exports variables that are not already set in the current shell.
# On macOS/Linux, source this file ("source ./set-caig-env-vars-sample.sh" or ". ./set-caig-env-vars-sample.sh")
# to export into your current shell session. Running it directly will create a subshell and
# not persist variables in your interactive shell.

echo "Preparing to set CAIG environment variables (will not overwrite existing variables)"

# Helper: export a variable only if it's not already defined or empty in the environment
set_env_if_missing() {
	local name="$1"
	local value="$2"

	# Use parameter expansion to check if variable is set and non-empty
	current_value="$(printf '%s' "${!name}")"

	if [ -n "$current_value" ]; then
		# Already set in this shell environment
		printf "%s => %s (exists, skipped)\n" "$name" "$current_value"
	else
		if [ -n "$value" ]; then
			# Export into current shell
			export "$name=$value"
			printf "%s => %s (set)\n" "$name" "$value"
		else
			# Value is an empty placeholder — skip to avoid accidental empty settings
			printf "%s => (no sample value, skipped)\n" "$name"
		fi
	fi
}

# Note: To persist variables permanently, add them to your shell profile (~/.bashrc, ~/.zshrc)
# or use a system-level mechanism; this script only affects the current shell when sourced.

set_env_if_missing CAIG_AZURE_OPENAI_COMPLETIONS_DEP "gpt-4.1"
set_env_if_missing CAIG_AZURE_OPENAI_EMBEDDINGS_DEP "text-embedding-ada-002"
set_env_if_missing CAIG_AZURE_OPENAI_KEY ""
set_env_if_missing CAIG_AZURE_OPENAI_URL ""
set_env_if_missing CAIG_CONFIG_CONTAINER "config"
set_env_if_missing CAIG_CONVERSATIONS_CONTAINER "conversations"
set_env_if_missing CAIG_COSMOSDB_NOSQL_ACCT "<your-account>"
set_env_if_missing CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM "key"
set_env_if_missing CAIG_COSMOSDB_NOSQL_KEY ""
set_env_if_missing CAIG_COSMOSDB_NOSQL_RG "<your-resource-group>"
set_env_if_missing CAIG_COSMOSDB_NOSQL_URI "https://<your-account>.documents.azure.com:443/"
set_env_if_missing CAIG_FEEDBACK_CONTAINER "xxx"
set_env_if_missing CAIG_GRAPH_DUMP_OUTFILE "tmp/model_dump.nt"
set_env_if_missing CAIG_GRAPH_DUMP_UPON_BUILD "false"
set_env_if_missing CAIG_GRAPH_NAMESPACE "http://cosmosdb.com/caig#"
set_env_if_missing CAIG_GRAPH_SERVICE_NAME "caig-graph"
set_env_if_missing CAIG_GRAPH_SERVICE_PORT "8001"
set_env_if_missing CAIG_GRAPH_SERVICE_URL "http://127.0.0.1"
set_env_if_missing CAIG_GRAPH_SOURCE_CONTAINER "libraries"
set_env_if_missing CAIG_GRAPH_SOURCE_DB "caig"
set_env_if_missing CAIG_GRAPH_SOURCE_OWL_FILENAME "ontologies/libraries.owl"
set_env_if_missing CAIG_GRAPH_SOURCE_PATH "rdf/libraries-graph.nt"
set_env_if_missing CAIG_GRAPH_SOURCE_TYPE "cosmos_nosql"
set_env_if_missing CAIG_HOME ""
set_env_if_missing CAIG_LOG_LEVEL "info"
set_env_if_missing CAIG_WEBSVC_AUTH_HEADER "xxx"
set_env_if_missing CAIG_WEBSVC_AUTH_VALUE "xxx"
set_env_if_missing CAIG_WEB_APP_NAME "caig-web"
set_env_if_missing CAIG_WEB_APP_PORT "8000"
set_env_if_missing CAIG_WEB_APP_URL "http://127.0.0.1"

############### Prompts
set_env_if_missing CAIG_PROMPT_SPARQL_PATH "prompts/gen_sparql_generic.txt"
set_env_if_missing CAIG_PROMPT_COMPLETION_PATH "prompts/gen_completion_generic.txt"

############ Azure Deployment
set_env_if_missing CAIG_ACA_ENVIRONMENT_NAME "caig"
set_env_if_missing CAIG_AZURE_REGION "eastus"
set_env_if_missing CAIG_DEFINED_AUTH_USERS "user1,user2,user3"
set_env_if_missing CAIG_LA_WORKSPACE_NAME "caig"

echo "Done. If you sourced this file, the variables are available in your shell session."
echo "To persist them, add the desired exports to ~/.bashrc, ~/.profile or ~/.zshrc as appropriate."