# PowerShell script to set the necessary CAIG_ environment variables,
# generated by main.py on Thu Oct  9 14:13:14 2025
# Edit ALL of these generated values per your actual deployment.

echo "Setting CAIG environment variables"

echo 'setting CAIG_AZURE_OPENAI_COMPLETIONS_DEP'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_OPENAI_COMPLETIONS_DEP", "gpt4o", "User")

echo 'setting CAIG_AZURE_OPENAI_EMBEDDINGS_DEP'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_OPENAI_EMBEDDINGS_DEP", "embeddings", "User")

echo 'setting CAIG_AZURE_OPENAI_KEY'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_OPENAI_KEY", "", "User")

echo 'setting CAIG_AZURE_OPENAI_URL'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_OPENAI_URL", "", "User")

echo 'setting CAIG_AZURE_OPENAI_VERSION'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_OPENAI_VERSION", "xxx", "User")

echo 'setting CAIG_CONFIG_CONTAINER'
[Environment]::SetEnvironmentVariable("CAIG_CONFIG_CONTAINER", "config", "User")

echo 'setting CAIG_CONVERSATIONS_CONTAINER'
[Environment]::SetEnvironmentVariable("CAIG_CONVERSATIONS_CONTAINER", "conversations", "User")

echo 'setting CAIG_COSMOSDB_NOSQL_ACCT'
[Environment]::SetEnvironmentVariable("CAIG_COSMOSDB_NOSQL_ACCT", "mycosmosdbnosqlacct", "User")

echo 'setting CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM'
[Environment]::SetEnvironmentVariable("CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM", "key", "User")

echo 'setting CAIG_COSMOSDB_NOSQL_KEY'
[Environment]::SetEnvironmentVariable("CAIG_COSMOSDB_NOSQL_KEY", "", "User")

echo 'setting CAIG_COSMOSDB_NOSQL_RG'
[Environment]::SetEnvironmentVariable("CAIG_COSMOSDB_NOSQL_RG", "myresourcegroup", "User")

echo 'setting CAIG_COSMOSDB_NOSQL_URI'
[Environment]::SetEnvironmentVariable("CAIG_COSMOSDB_NOSQL_URI", "https://<your-account>.documents.azure.com:443/", "User")

echo 'setting CAIG_FEEDBACK_CONTAINER'
[Environment]::SetEnvironmentVariable("CAIG_FEEDBACK_CONTAINER", "xxx", "User")

echo 'setting CAIG_GRAPH_DUMP_OUTFILE'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_DUMP_OUTFILE", "", "User")

echo 'setting CAIG_GRAPH_DUMP_UPON_BUILD'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_DUMP_UPON_BUILD", "false", "User")

echo 'setting CAIG_GRAPH_NAMESPACE'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_NAMESPACE", "", "User")

echo 'setting CAIG_GRAPH_SERVICE_NAME'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SERVICE_NAME", "caig-graph", "User")

echo 'setting CAIG_GRAPH_SERVICE_PORT'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SERVICE_PORT", "8001", "User")

echo 'setting CAIG_GRAPH_SERVICE_URL'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SERVICE_URL", "http://127.0.0.1", "User")

echo 'setting CAIG_GRAPH_SOURCE_CONTAINER'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SOURCE_CONTAINER", "libraries", "User")

echo 'setting CAIG_GRAPH_SOURCE_DB'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SOURCE_DB", "caig", "User")

echo 'setting CAIG_GRAPH_SOURCE_OWL_FILENAME'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SOURCE_OWL_FILENAME", "ontologies/extracted_ontology.ttl", "User")

echo 'setting CAIG_GRAPH_SOURCE_PATH'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SOURCE_PATH", "xxx", "User")

echo 'setting CAIG_GRAPH_SOURCE_TYPE'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SOURCE_TYPE", "cosmos_nosql", "User")

echo 'setting CAIG_HOME'
[Environment]::SetEnvironmentVariable("CAIG_HOME", "", "User")

echo 'setting CAIG_LOG_LEVEL'
[Environment]::SetEnvironmentVariable("CAIG_LOG_LEVEL", "info", "User")

echo 'setting CAIG_PROMPT_COMPLETION_PATH'
[Environment]::SetEnvironmentVariable("CAIG_PROMPT_COMPLETION_PATH", "prompts/gen_completion_generic.txt", "User")

echo 'setting CAIG_PROMPT_SPARQL_PATH'
[Environment]::SetEnvironmentVariable("CAIG_PROMPT_SPARQL_PATH", "prompts/gen_sparql_generic.txt", "User")

echo 'setting CAIG_WEBSVC_AUTH_HEADER'
[Environment]::SetEnvironmentVariable("CAIG_WEBSVC_AUTH_HEADER", "xxx", "User")

echo 'setting CAIG_WEBSVC_AUTH_VALUE'
[Environment]::SetEnvironmentVariable("CAIG_WEBSVC_AUTH_VALUE", "xxx", "User")

echo 'setting CAIG_WEB_APP_NAME'
[Environment]::SetEnvironmentVariable("CAIG_WEB_APP_NAME", "caig-web", "User")

echo 'setting CAIG_WEB_APP_PORT'
[Environment]::SetEnvironmentVariable("CAIG_WEB_APP_PORT", "8000", "User")

echo 'setting CAIG_WEB_APP_URL'
[Environment]::SetEnvironmentVariable("CAIG_WEB_APP_URL", "http://127.0.0.1", "User")

