# Docker Compose script to run both microservices (web, graph) locally.
# Use of this script:
#   docker compose -f docker/docker-compose.yml up
#   docker compose -f docker/docker-compose.yml down   (in a second terminal window)
# Docker Image Notes:
#   caig_web and caig_graph support Cosmos DB vCore API only
#   caig_web_v2 and caig_graph_v2 support either Cosmos DB vCore API or Cosmos DB SQL API
# Chris Joakim, Microsoft

services:

  web_app:
    image: cjoakim/caig_web_v2:latest
    ports:
      - "8000:8000"
    volumes:
      - ./tmp:/tmp:rw
    environment:
      CAIG_ACA_ENVIRONMENT_NAME:          $CAIG_ACA_ENVIRONMENT_NAME
      CAIG_AZURE_MONGO_VCORE_CONN_STR:    $CAIG_AZURE_MONGO_VCORE_CONN_STR
      CAIG_AZURE_OPENAI_COMPLETIONS_DEP:  $CAIG_AZURE_OPENAI_COMPLETIONS_DEP
      CAIG_AZURE_OPENAI_EMBEDDINGS_DEP:   $CAIG_AZURE_OPENAI_EMBEDDINGS_DEP
      CAIG_AZURE_OPENAI_KEY:              $CAIG_AZURE_OPENAI_KEY
      CAIG_AZURE_OPENAI_URL:              $CAIG_AZURE_OPENAI_URL
      CAIG_AZURE_REGION:                  $CAIG_AZURE_REGION
      CAIG_CONFIG_CONTAINER:              $CAIG_CONFIG_CONTAINER
      CAIG_CONVERSATIONS_CONTAINER:       $CAIG_CONVERSATIONS_CONTAINER
      CAIG_COSMOSDB_NOSQL_ACCT:           $CAIG_COSMOSDB_NOSQL_ACCT
      CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM: $CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM
      CAIG_COSMOSDB_NOSQL_KEY1:           $CAIG_COSMOSDB_NOSQL_KEY1
      CAIG_COSMOSDB_NOSQL_RG:             $CAIG_COSMOSDB_NOSQL_RG
      CAIG_COSMOSDB_NOSQL_URI:            $CAIG_COSMOSDB_NOSQL_URI
      CAIG_DEFINED_AUTH_USERS:            $CAIG_DEFINED_AUTH_USERS
      CAIG_ENCRYPTION_SYMMETRIC_KEY:      $CAIG_ENCRYPTION_SYMMETRIC_KEY
      CAIG_FEEDBACK_CONTAINER:            $CAIG_FEEDBACK_CONTAINER
      CAIG_GRAPH_NAMESPACE:               $CAIG_GRAPH_NAMESPACE
      CAIG_GRAPH_SERVICE_NAME:            $CAIG_GRAPH_SERVICE_NAME
      CAIG_GRAPH_SERVICE_PORT:            $CAIG_GRAPH_SERVICE_PORT
      CAIG_GRAPH_SOURCE_CONTAINER:        $CAIG_GRAPH_SOURCE_CONTAINER
      CAIG_GRAPH_SOURCE_DB:               $CAIG_GRAPH_SOURCE_DB
      CAIG_GRAPH_SOURCE_OWL_FILENAME:     $CAIG_GRAPH_SOURCE_OWL_FILENAME
      CAIG_GRAPH_SOURCE_RDF_FILENAME:     $CAIG_GRAPH_SOURCE_RDF_FILENAME
      CAIG_GRAPH_SOURCE_TYPE:             $CAIG_GRAPH_SOURCE_TYPE
      CAIG_LA_WORKSPACE_NAME:             $CAIG_LA_WORKSPACE_NAME
      CAIG_LOG_LEVEL:                     $CAIG_LOG_LEVEL
      CAIG_WEBSVC_AUTH_HEADER:            $CAIG_WEBSVC_AUTH_HEADER
      CAIG_WEBSVC_AUTH_VALUE:             $CAIG_WEBSVC_AUTH_VALUE
      CAIG_WEB_APP_NAME:                  $CAIG_WEB_APP_NAME
      CAIG_GRAPH_SERVICE_URL:             http://graph_service
      PORT:                               8000
      WEB_CONCURRENCY:                    1

  graph_service:
    image: cjoakim/caig_graph_v2:latest
    ports:
      - "8001:8001"
    volumes:
      - ./tmp:/tmp:rw
    environment:
      CAIG_ACA_ENVIRONMENT_NAME:          $CAIG_ACA_ENVIRONMENT_NAME
      CAIG_AZURE_MONGO_VCORE_CONN_STR:    $CAIG_AZURE_MONGO_VCORE_CONN_STR
      CAIG_AZURE_OPENAI_COMPLETIONS_DEP:  $CAIG_AZURE_OPENAI_COMPLETIONS_DEP
      CAIG_AZURE_OPENAI_EMBEDDINGS_DEP:   $CAIG_AZURE_OPENAI_EMBEDDINGS_DEP
      CAIG_AZURE_OPENAI_KEY:              $CAIG_AZURE_OPENAI_KEY
      CAIG_AZURE_OPENAI_URL:              $CAIG_AZURE_OPENAI_URL
      CAIG_AZURE_REGION:                  $CAIG_AZURE_REGION
      CAIG_CONFIG_CONTAINER:              $CAIG_CONFIG_CONTAINER
      CAIG_CONVERSATIONS_CONTAINER:       $CAIG_CONVERSATIONS_CONTAINER
      CAIG_COSMOSDB_NOSQL_ACCT:           $CAIG_COSMOSDB_NOSQL_ACCT
      CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM: $CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM
      CAIG_COSMOSDB_NOSQL_KEY1:           $CAIG_COSMOSDB_NOSQL_KEY1
      CAIG_COSMOSDB_NOSQL_RG:             $CAIG_COSMOSDB_NOSQL_RG
      CAIG_COSMOSDB_NOSQL_URI:            $CAIG_COSMOSDB_NOSQL_URI
      CAIG_DEFINED_AUTH_USERS:            $CAIG_DEFINED_AUTH_USERS
      CAIG_ENCRYPTION_SYMMETRIC_KEY:      $CAIG_ENCRYPTION_SYMMETRIC_KEY
      CAIG_FEEDBACK_CONTAINER:            $CAIG_FEEDBACK_CONTAINER
      CAIG_GRAPH_NAMESPACE:               $CAIG_GRAPH_NAMESPACE
      CAIG_GRAPH_SERVICE_NAME:            $CAIG_GRAPH_SERVICE_NAME
      CAIG_GRAPH_SERVICE_PORT:            $CAIG_GRAPH_SERVICE_PORT
      CAIG_GRAPH_SERVICE_URL:             $CAIG_GRAPH_SERVICE_URL
      CAIG_GRAPH_SOURCE_CONTAINER:        $CAIG_GRAPH_SOURCE_CONTAINER
      CAIG_GRAPH_SOURCE_DB:               $CAIG_GRAPH_SOURCE_DB
      CAIG_GRAPH_SOURCE_OWL_FILENAME:     $CAIG_GRAPH_SOURCE_OWL_FILENAME
      CAIG_GRAPH_SOURCE_RDF_FILENAME:     $CAIG_GRAPH_SOURCE_RDF_FILENAME
      CAIG_GRAPH_SOURCE_TYPE:             $CAIG_GRAPH_SOURCE_TYPE
      CAIG_LA_WORKSPACE_NAME:             $CAIG_LA_WORKSPACE_NAME
      CAIG_LOG_LEVEL:                     $CAIG_LOG_LEVEL
      CAIG_WEBSVC_AUTH_HEADER:            $CAIG_WEBSVC_AUTH_HEADER
      CAIG_WEBSVC_AUTH_VALUE:             $CAIG_WEBSVC_AUTH_VALUE
      CAIG_WEB_APP_NAME:                  $CAIG_WEB_APP_NAME
      PORT:                               8001
      WEB_CONCURRENCY:                    1


# WEB_CONCURRENCY relates to uvicorn and the --workers count; see https://www.uvicorn.org

# Use of this script:
# docker compose -f docker/docker-compose.yml up
# docker compose -f docker/docker-compose.yml down   (in a second terminal window)
