// Bicep bicepparam entries generated by main.py on Sat Mar  8 18:14:39 2025
// Include these in your caig.bicepparam file

using './caig.bicep'

param azureOpenaiCompletionsDep = readEnvironmentVariable('CAIG_AZURE_OPENAI_COMPLETIONS_DEP')
param azureOpenaiEmbeddingsDep = readEnvironmentVariable('CAIG_AZURE_OPENAI_EMBEDDINGS_DEP')
param azureOpenaiKey = readEnvironmentVariable('CAIG_AZURE_OPENAI_KEY')
param azureOpenaiUrl = readEnvironmentVariable('CAIG_AZURE_OPENAI_URL')
param configContainer = readEnvironmentVariable('CAIG_CONFIG_CONTAINER')
param conversationsContainer = readEnvironmentVariable('CAIG_CONVERSATIONS_CONTAINER')
param cosmosdbNosqlAcct = readEnvironmentVariable('CAIG_COSMOSDB_NOSQL_ACCT')
param cosmosdbNosqlAuthMechanism = readEnvironmentVariable('CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM')
param cosmosdbNosqlKey = readEnvironmentVariable('CAIG_COSMOSDB_NOSQL_KEY')
param cosmosdbNosqlRg = readEnvironmentVariable('CAIG_COSMOSDB_NOSQL_RG')
param cosmosdbNosqlUri = readEnvironmentVariable('CAIG_COSMOSDB_NOSQL_URI')
param feedbackContainer = readEnvironmentVariable('CAIG_FEEDBACK_CONTAINER')
param graphDumpOutfile = readEnvironmentVariable('CAIG_GRAPH_DUMP_OUTFILE')
param graphDumpUponBuild = readEnvironmentVariable('CAIG_GRAPH_DUMP_UPON_BUILD')
param graphNamespace = readEnvironmentVariable('CAIG_GRAPH_NAMESPACE')
param graphServiceName = readEnvironmentVariable('CAIG_GRAPH_SERVICE_NAME')
param graphServicePort = readEnvironmentVariable('CAIG_GRAPH_SERVICE_PORT')
param graphServiceUrl = readEnvironmentVariable('CAIG_GRAPH_SERVICE_URL')
param graphSourceContainer = readEnvironmentVariable('CAIG_GRAPH_SOURCE_CONTAINER')
param graphSourceDb = readEnvironmentVariable('CAIG_GRAPH_SOURCE_DB')
param graphSourceOwlFilename = readEnvironmentVariable('CAIG_GRAPH_SOURCE_OWL_FILENAME')
param graphSourceRdfFilename = readEnvironmentVariable('CAIG_GRAPH_SOURCE_PATH')
param graphSourceType = readEnvironmentVariable('CAIG_GRAPH_SOURCE_TYPE')
param logLevel = readEnvironmentVariable('CAIG_LOG_LEVEL')
param websvcAuthHeader = readEnvironmentVariable('CAIG_WEBSVC_AUTH_HEADER')
param websvcAuthValue = readEnvironmentVariable('CAIG_WEBSVC_AUTH_VALUE')
param webAppName = readEnvironmentVariable('CAIG_WEB_APP_NAME')

