# Docker Compose script to run just the Java-based graph_service.
# Use of this script:
#   docker compose -f docker-compose-graph-only.yml up
#   docker compose -f docker-compose-graph-only.yml down  (in a second terminal window)
# Chris Joakim, Microsoft, 2025

services:
  graph_service:
    image: cjoakim/caig_graph_java_jena_v1:latest
    ports:
      - "8001:8001"
    volumes:
      - ./tmp:/tmp:rw
    environment:
      CAIG_COSMOSDB_NOSQL_ACCT:            $CAIG_COSMOSDB_NOSQL_ACCT
      CAIG_COSMOSDB_NOSQL_URI:             $CAIG_COSMOSDB_NOSQL_URI
      CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM:  key
      CAIG_COSMOSDB_NOSQL_KEY:             $CAIG_COSMOSDB_NOSQL_KEY
      CAIG_GRAPH_SOURCE_TYPE:              cosmos_nosql
      CAIG_GRAPH_SOURCE_DB:                $CAIG_GRAPH_SOURCE_DB
      CAIG_GRAPH_SOURCE_CONTAINER:         $CAIG_GRAPH_SOURCE_CONTAINER
      CAIG_GRAPH_SOURCE_OWL_FILENAME:      $CAIG_GRAPH_SOURCE_OWL_FILENAME
      CAIG_GRAPH_SOURCE_RDF_FILENAME:      $CAIG_GRAPH_SOURCE_RDF_FILENAME
      CAIG_GRAPH_NAMESPACE:                $CAIG_GRAPH_NAMESPACE
      CAIG_GRAPH_DUMP_UPON_BUILD:          false
      CAIG_GRAPH_DUMP_OUTFILE:             tmp/model_dump.nt
      PORT:                                8001
